version: '3'

volumes:
  bulks:

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    restart: always
    ports:
      - 3030:9000
    #volumes:
    #  - 'bulks:/home/pn/bulk'
